# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:26
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add title', max_length=50)),
                ('description', models.TextField(help_text='Add topic description')),
                ('status', models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Finished', 'Finished')], default='Inactive', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='assignment_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment', models.ForeignKey(help_text='Add assignment', on_delete=django.db.models.deletion.CASCADE, to='eclass.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add topic title', max_length=100)),
                ('description', models.TextField(help_text='Add topic description')),
            ],
        ),
        migrations.CreateModel(
            name='Completed_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateField(default=datetime.datetime(2017, 12, 4, 22, 26, 52, 282865))),
                ('score', models.CharField(help_text='Add scores', max_length=5)),
                ('assignment', models.ForeignKey(help_text='Add assignment', on_delete=django.db.models.deletion.CASCADE, to='eclass.assignment')),
            ],
        ),
        migrations.CreateModel(
            name='course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add course title', max_length=100)),
                ('description', models.TextField(help_text='Add course description')),
                ('picture', models.FileField(upload_to='courses')),
            ],
        ),
        migrations.CreateModel(
            name='course_for',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('course', models.ForeignKey(help_text='Add course', on_delete=django.db.models.deletion.CASCADE, to='eclass.course')),
            ],
        ),
        migrations.CreateModel(
            name='eclass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Add class', max_length=50)),
                ('description', models.TextField(help_text='Add the description')),
            ],
        ),
        migrations.CreateModel(
            name='note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add topic title', max_length=100)),
                ('description', models.TextField(blank=True, help_text='Add topic description', null=True)),
                ('document', models.FileField(blank=True, help_text='Add a document file', null=True, upload_to='chapters')),
                ('doc_title', models.CharField(blank=True, default="Add the file's title", help_text='Add file title', max_length=100, null=True)),
                ('file_type', models.CharField(blank=True, choices=[('Image', 'Image'), ('Other', 'Other')], default='Image', max_length=200, null=True)),
                ('file_description', models.TextField(blank=True, help_text='Add file description', null=True)),
                ('chapter', models.ForeignKey(help_text='Choose a chapter', on_delete=django.db.models.deletion.CASCADE, to='eclass.chapter')),
            ],
        ),
        migrations.CreateModel(
            name='qchoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(help_text='Enter option', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='qtype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter name for the type', max_length=50)),
                ('code', models.CharField(help_text='Enter code for the type', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(help_text='Enter question')),
                ('document', models.FileField(blank=True, help_text='Add a document file', null=True, upload_to='chapters')),
                ('answer', models.TextField(help_text='Add the correct answer')),
                ('assignment', models.ForeignKey(help_text='Assignment', on_delete=django.db.models.deletion.CASCADE, to='eclass.assignment')),
                ('q_type', models.ForeignKey(help_text='Choose question type', on_delete=django.db.models.deletion.CASCADE, to='eclass.qtype')),
            ],
        ),
        migrations.CreateModel(
            name='student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Add First name', max_length=100)),
                ('last_name', models.CharField(help_text='Add Last name', max_length=100)),
                ('email', models.EmailField(help_text='Add Email', max_length=254)),
                ('id_number', models.CharField(help_text='Add ID', max_length=50)),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('created', 'created')], default='Pending', max_length=20)),
                ('eclass', models.ForeignKey(help_text='Choose a class', on_delete=django.db.models.deletion.CASCADE, to='eclass.eclass')),
                ('username', models.ForeignKey(help_text='Associated user', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Add topic title', max_length=100)),
                ('description', models.TextField(help_text='Add topic description')),
                ('course', models.ForeignKey(help_text='Choose a course', on_delete=django.db.models.deletion.CASCADE, to='eclass.course')),
            ],
        ),
        migrations.AddField(
            model_name='qchoice',
            name='q_type',
            field=models.ForeignKey(help_text='Choose question type', on_delete=django.db.models.deletion.CASCADE, to='eclass.qtype'),
        ),
        migrations.AddField(
            model_name='qchoice',
            name='question',
            field=models.ForeignKey(help_text='Choose question type', on_delete=django.db.models.deletion.CASCADE, to='eclass.question'),
        ),
        migrations.AddField(
            model_name='course_for',
            name='eclass',
            field=models.ForeignKey(help_text='Add class', on_delete=django.db.models.deletion.CASCADE, to='eclass.eclass'),
        ),
        migrations.AddField(
            model_name='completed_assignment',
            name='student',
            field=models.ForeignKey(help_text='Add class', on_delete=django.db.models.deletion.CASCADE, to='eclass.student'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='topic',
            field=models.ForeignKey(help_text='Choose a topic', on_delete=django.db.models.deletion.CASCADE, to='eclass.topic'),
        ),
        migrations.AddField(
            model_name='assignment_for',
            name='eclass',
            field=models.ForeignKey(help_text='Add class', on_delete=django.db.models.deletion.CASCADE, to='eclass.eclass'),
        ),
    ]
