# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 22:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0002_auto_20171204_2227'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assignment_for',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='assignment_for',
            name='eclass',
        ),
        migrations.RemoveField(
            model_name='chapter',
            name='topic',
        ),
        migrations.RemoveField(
            model_name='completed_assignment',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='completed_assignment',
            name='student',
        ),
        migrations.RemoveField(
            model_name='course_for',
            name='course',
        ),
        migrations.RemoveField(
            model_name='course_for',
            name='eclass',
        ),
        migrations.RemoveField(
            model_name='note',
            name='chapter',
        ),
        migrations.RemoveField(
            model_name='qchoice',
            name='q_type',
        ),
        migrations.RemoveField(
            model_name='qchoice',
            name='question',
        ),
        migrations.RemoveField(
            model_name='question',
            name='assignment',
        ),
        migrations.RemoveField(
            model_name='question',
            name='q_type',
        ),
        migrations.RemoveField(
            model_name='student',
            name='eclass',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
        migrations.RemoveField(
            model_name='topic',
            name='course',
        ),
        migrations.DeleteModel(
            name='assignment',
        ),
        migrations.DeleteModel(
            name='assignment_for',
        ),
        migrations.DeleteModel(
            name='chapter',
        ),
        migrations.DeleteModel(
            name='Completed_assignment',
        ),
        migrations.DeleteModel(
            name='course',
        ),
        migrations.DeleteModel(
            name='course_for',
        ),
        migrations.DeleteModel(
            name='eclass',
        ),
        migrations.DeleteModel(
            name='note',
        ),
        migrations.DeleteModel(
            name='qchoice',
        ),
        migrations.DeleteModel(
            name='qtype',
        ),
        migrations.DeleteModel(
            name='question',
        ),
        migrations.DeleteModel(
            name='student',
        ),
        migrations.DeleteModel(
            name='topic',
        ),
    ]
