# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 10:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0004_auto_20171204_2235'),
    ]

    operations = [
        migrations.CreateModel(
            name='current',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(help_text='Choose a student', on_delete=django.db.models.deletion.CASCADE, to='eclass.student')),
                ('topic', models.ForeignKey(help_text='Choosea topic', on_delete=django.db.models.deletion.CASCADE, to='eclass.topic')),
            ],
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 5, 10, 56, 51, 776671)),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Image', 'Image')], default='Image', max_length=200, null=True),
        ),
    ]
