# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-05 19:28
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0005_auto_20171205_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='current',
            name='chapter',
            field=models.ForeignKey(default=1, help_text='Choose chapter', on_delete=django.db.models.deletion.CASCADE, to='eclass.chapter'),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Finished', 'Finished')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 5, 19, 28, 50, 989260)),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('created', 'created')], default='Pending', max_length=20),
        ),
    ]
