# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:23
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0006_auto_20171205_1928'),
    ]

    operations = [
        migrations.CreateModel(
            name='incompleted_assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Finished', 'Finished')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 6, 16, 23, 52, 845702)),
        ),
        migrations.AddField(
            model_name='incompleted_assignment',
            name='assignment',
            field=models.ForeignKey(help_text='Add assignment', on_delete=django.db.models.deletion.CASCADE, to='eclass.assignment'),
        ),
    ]
