# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0008_auto_20171206_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='invited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(help_text='Add First name', max_length=100)),
                ('last_name', models.CharField(help_text='Add Last name', max_length=100)),
                ('email', models.EmailField(help_text='Add Email', max_length=254)),
                ('id_number', models.CharField(help_text='Add ID', max_length=50, unique=True)),
                ('eclass', models.ForeignKey(help_text='Choose a class', on_delete=django.db.models.deletion.CASCADE, to='eclass.eclass')),
            ],
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 11, 26, 18, 696785)),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Image', 'Image')], default='Image', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='id_number',
            field=models.CharField(help_text='Add ID', max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('created', 'created')], default='Pending', max_length=20),
        ),
    ]
