# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 11:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0009_auto_20171207_1126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invited',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invited',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Active', 'Active'), ('Finished', 'Finished')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 11, 54, 27, 46408)),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Image', 'Image'), ('Other', 'Other')], default='Image', max_length=200, null=True),
        ),
    ]
