# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:53
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0010_auto_20171207_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 13, 53, 20, 976696)),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
