# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 13:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0014_auto_20171207_1356'),
    ]

    operations = [
        migrations.CreateModel(
            name='invited',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(help_text='Add Email', max_length=254)),
                ('id_number', models.CharField(help_text='Add ID', max_length=50, unique=True)),
                ('eclass', models.ForeignKey(help_text='Choose a class', on_delete=django.db.models.deletion.CASCADE, to='eclass.eclass')),
            ],
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Inactive', 'Inactive'), ('Finished', 'Finished'), ('Active', 'Active')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 13, 58, 24, 635001)),
        ),
    ]
