# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:12
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0015_auto_20171207_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='invited',
            name='first_name',
            field=models.CharField(default='First name', help_text='Add First name', max_length=100),
        ),
        migrations.AddField(
            model_name='invited',
            name='last_name',
            field=models.CharField(default='Last name', help_text='Add Last name', max_length=100),
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 14, 12, 34, 734470)),
        ),
        migrations.AlterField(
            model_name='note',
            name='file_type',
            field=models.CharField(blank=True, choices=[('Other', 'Other'), ('Image', 'Image')], default='Image', max_length=200, null=True),
        ),
    ]
