# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0016_auto_20171207_1412'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invited',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='invited',
            name='last_name',
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Finished', 'Finished'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 14, 39, 14, 310394)),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('created', 'created'), ('Pending', 'Pending')], default='Pending', max_length=20),
        ),
    ]
