# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-07 14:39
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0017_auto_20171207_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 7, 14, 39, 29, 687199)),
        ),
    ]
