# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 07:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eclass', '0018_auto_20171207_1439'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment_for',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive')], default='Inactive', max_length=20),
        ),
        migrations.AlterField(
            model_name='completed_assignment',
            name='time',
            field=models.DateField(default=datetime.datetime(2017, 12, 11, 7, 26, 2, 790811)),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('created', 'created')], default='Pending', max_length=20),
        ),
    ]
